config/routes.rb
Rails.application.routes.draw do

  devise_for :admins

  namespace :admin do
    resources :about, :skills, :projects, :contacts
  end

  namespace :user do
    resources :about,:skills, :projects, :contacts ,only: [:index, :show]
  end
  get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root to: "home#index"
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/admin.rb
class Admin < ApplicationRecord
  has_many :contacts
  has_many :skills
  has_many :projects
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable




end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contact.rb
class Contact < ApplicationRecord
    belongs_to :admin

    # Fields required
    validates_presence_of :contact_name
    validates_presence_of :contact_email
    validates_presence_of :contact_option
    validates_presence_of :contact_message
    validates_format_of :contact_email, with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

    scope :hire_only, -> {where(contact_option:'hire')}


end

app/models/project.rb
class Project < ApplicationRecord
    belongs_to :admin

    # Fields required
    validates_presence_of :project_name
    validates_presence_of :project_description
    validates_presence_of :project_stack
    validates_presence_of :project_task
    validates_presence_of :project_start_date
    validates_presence_of :project_end_date

    




    

end

app/models/skill.rb
class Skill < ApplicationRecord
    belongs_to :admin

    # Fields required
    validates_presence_of :skill_type
    validates_presence_of :skill_description

    scope :soft_skills_only, -> {where(skill_type:'soft')}
    scope :hard_skills_only, -> {where(skill_type:'hard')}


end

app/controllers/admin/about_controller.rb
class Admin::AboutController < ApplicationController
    before_action :authenticate_admin!

    def index
        
    end
    def show
      
    end

    

end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @projects = Project.all
  end

  def show
    @project = Project.find(params[:id])
    
  end

  def new
    @project = Project.new
  end  

  def create
    @project = Project.new(project_params)

    if @project.save
    #  se guardo el proyecto
      flash[:notice] = 'A new project has been created!'
      redirect_to admin_projects_path
    else

      flash[:error] = 'Error can not create the new project!'
      render :new, status: 422
      
    end
  end

  def edit
    @project = Project.find(params[:id])
  end
  
  def update
    @project = Project.find(params[:id])

    if @project.update(project_params)
      flash[:notice] = 'The project has been edited!'
      redirect_to @project
    else
      flash[:error] = 'Error can not create the project!'
      render :edit, status: 422

    end  

  end

  private

  def project_params
    # params.require(:project).permit(:project_name, :project_description, :project_stack, :project_start_date, :project_end_date, :admin_id)
    new_params = {
      project_name: params[:project_name],
      project_description: params[:project_description],
      project_stack: params[:project_stack],
      project_task: params[:project_task],
      project_start_date: params[:project_start_date],
      project_end_date: params[:project_end_date],
      admin_id: params[:admin_id]
    }
    new_params
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_admin!
  def index
  end
end

app/controllers/user/about_controller.rb
class User::AboutController < ApplicationController
  def index
  end
end

app/controllers/user/projects_controller.rb
class User::ProjectsController < ApplicationController
  def index
  end
end

app/helpers/admin/about_helper.rb
module Admin::AboutHelper
end

app/helpers/admin/contact_helper.rb
module Admin::ContactHelper
end

app/helpers/admin/contacts_helper.rb
module Admin::ContactsHelper
end

app/helpers/admin/projects_helper.rb
module Admin::ProjectsHelper
end

app/helpers/admin/skills_helper.rb
module Admin::SkillsHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/user/about_helper.rb
module User::AboutHelper
end

app/helpers/user/contact_helper.rb
module User::ContactHelper
end

app/helpers/user/contacts_helper.rb
module User::ContactsHelper
end

app/helpers/user/projects_helper.rb
module User::ProjectsHelper
end

app/helpers/user/skills_helper.rb
module User::SkillsHelper
end

app/views/admin/projects/_form.html.erb
<div class='flash-error'>
        <% if flash[:error].present?%>
            <%= flash[:error]%>
        <% end %>
</div>


<% if project.blank? %>
    <strong>No hay projects aun</strong>

    <% elsif view == 'new' %>
<section  class= ''>

    <%= form_with(model: @admin_project, url: admin_projects_path) do |project_form| %>

        <%= project_form.label :name %>
        <%= project_form.text_field :project_name %>

    <% if @project.errors[:project_name].present?%>
        <ul class = 'error-list'>
            <%@project.errors[:project_name].each do | error_message| %>
                <li> <%= error_message%> </li>
            <% end%>
        </ul> 
    <% end %>

        <%= project_form.label :description %>
        <%= project_form.text_field :project_description %>

    <% if @project.errors[:project_description].present?%>
        <ul class = 'error-list'>
            <%@project.errors[:project_description].each do | error_message| %>
                <li> <%= error_message%> </li>
            <% end%>
        </ul> 
    <% end %>
        <br>
        <br>

        <%= project_form.label :stack %>
        <%= project_form.text_field :project_stack %>

    <% if @project.errors[:project_stack].present?%>
        <ul class = 'error-list'>
            <%@project.errors[:project_stack].each do | error_message| %>
                <li> <%= error_message%> </li>
            <% end%>
        </ul> 
    <% end %>


        <%= project_form.label :task %>
        <%= project_form.text_field :project_task %>

    <% if @project.errors[:project_task].present?%>
        <ul class = 'error-list'>
            <%@project.errors[:project_task].each do | error_message| %>
                <li> <%= error_message%> </li>
            <% end%>
        </ul> 
    <% end %>


        <%= project_form.label :start %>
        <%= project_form.text_field :project_start_date %>

    <% if @project.errors[:project_start_date].present?%>
        <ul class = 'error-list'>
            <%@project.errors[:project_start_date].each do | error_message| %>
                <li> <%= error_message%> </li>
            <% end%>
        </ul> 
    <% end %>


        <%= project_form.label :end %>
        <%= project_form.text_field :project_end_date %>

    <% if @project.errors[:project_end_date].present?%>
        <ul class = 'error-list'>
            <%@project.errors[:project_end_date].each do | error_message| %>
                <li> <%= error_message%> </li>
            <% end%>
        </ul> 
    <% end %>
        
        <%= project_form.label :id %>
        <%= project_form.text_field :admin_id %>

    <% if @project.errors[:admin_id].present?%>
        <ul class = 'error-list'>
            <%@project.errors[:admin_id].each do | error_message| %>
                <li> <%= error_message%> </li>
            <% end%>
        </ul> 
    <% end %>
        <%= project_form.submit%>


            <% end  %>

</section>

<% else %>

<section  class= ''>

    <%= form_with(model: @admin_project, url: admin_projects_path) do |project_form| %>

        <%= project_form.label :name %>
        <%= project_form.text_field :project_name %>

    <% if @project.errors[:project_name].present?%>
        <ul class = 'error-list'>
            <%@project.errors[:project_name].each do | error_message| %>
                <li> <%= error_message%> </li>
            <% end%>
        </ul> 
    <% end %>

        <%= project_form.label :description %>
        <%= project_form.text_field :project_description %>

    <% if @project.errors[:project_description].present?%>
        <ul class = 'error-list'>
            <%@project.errors[:project_description].each do | error_message| %>
                <li> <%= error_message%> </li>
            <% end%>
        </ul> 
    <% end %>
        <br>
        <br>

        <%= project_form.label :stack %>
        <%= project_form.text_field :project_stack %>

    <% if @project.errors[:project_stack].present?%>
        <ul class = 'error-list'>
            <%@project.errors[:project_stack].each do | error_message| %>
                <li> <%= error_message%> </li>
            <% end%>
        </ul> 
    <% end %>


        <%= project_form.label :task %>
        <%= project_form.text_field :project_task %>

    <% if @project.errors[:project_task].present?%>
        <ul class = 'error-list'>
            <%@project.errors[:project_task].each do | error_message| %>
                <li> <%= error_message%> </li>
            <% end%>
        </ul> 
    <% end %>


        <%= project_form.label :start %>
        <%= project_form.text_field :project_start_date %>

    <% if @project.errors[:project_start_date].present?%>
        <ul class = 'error-list'>
            <%@project.errors[:project_start_date].each do | error_message| %>
                <li> <%= error_message%> </li>
            <% end%>
        </ul> 
    <% end %>


        <%= project_form.label :end %>
        <%= project_form.text_field :project_end_date %>

    <% if @project.errors[:project_end_date].present?%>
        <ul class = 'error-list'>
            <%@project.errors[:project_end_date].each do | error_message| %>
                <li> <%= error_message%> </li>
            <% end%>
        </ul> 
    <% end %>
        
        <%= project_form.label :id %>
        <%= project_form.text_field :admin_id %>

    <% if @project.errors[:admin_id].present?%>
        <ul class = 'error-list'>
            <%@project.errors[:admin_id].each do | error_message| %>
                <li> <%= error_message%> </li>
            <% end%>
        </ul> 
    <% end %>
        <%= project_form.submit%>


            <% end  %>

</section>

<% end%>    

app/views/admin/projects/edit.html.erb
<h1>Edit</h1>
<%= render partial: 'form', locals: { project: @project, view: 'edit' } %>

app/views/admin/projects/index.html.erb
<h1>Admin::Projects#index</h1>
<p>Find me in app/views/admin/projects/index.html.erb</p>

<main>

<section class='admin-project-menu'>
    <h2>Options</h2>
     <%=  link_to 'Create',  new_admin_project_path  %> 
     <br> <br>
    
    <% @projects.each do |project| %>
      <%= link_to 'Edit', edit_admin_project_path(project) %>
      <br> <br>
    <% end %>     
    
    
    <br> <br>



</section>

</main>

app/views/admin/projects/new.html.erb
<h1>Lets starting adding a new project to your portafolio</h1>

<%= render partial: 'form', locals: { project: @project, view: 'new' } %>